FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json nest-cli.json ./

COPY libs/ ./libs/

RUN npm config set fetch-retries 5
RUN npm config set fetch-retry-mintimeout 20000
RUN npm install


COPY apps/ ./apps/

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]