FROM node:20-alpine

RUN apk add --no-cache procps

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

COPY libs/ ./libs/

RUN npm config set fetch-retries 5
RUN npm config set fetch-retry-mintimeout 20000
RUN npm install

CMD ["npm", "run", "start:dev"]