FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./
COPY libs/ ./libs/

COPY apps/frontend/package*.json ./apps/frontend/

RUN npm config set fetch-retries 5
RUN npm config set fetch-retry-mintimeout 20000
RUN npm install

WORKDIR /usr/src/app/apps/frontend
RUN npm install

CMD ["npm", "run", "dev", "--", "--host"]