FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm config set fetch-retries 5
RUN npm config set fetch-retry-mintimeout 20000
RUN npm install

CMD ["npm", "run", "dev", "--", "--host"]